# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Build
      run: | 
        GOOS=linux GOARCH=amd64 go build -o lxc-ui-api-linux-amd64 main.go
        GOOS=linux GOARCH=arm64 go build -o lxc-ui-api-linux-arm64 main.go
        GOOS=android GOARCH=arm64 go build -o lxc-ui-api-android-arm64 main.go

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: lxc-ui-api-linux-amd64
        path: |
          ./lxc-ui-api-linux-amd64
          
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: lxc-ui-api-linux-arm64
        path: |
          ./lxc-ui-api-linux-arm64
          
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: lxc-ui-api-android-arm64
        path: |
          ./lxc-ui-api-android-arm64
